clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
  build:
    image: klakegg/hugo:ext-alpine
    commands:
      - hugo -D
  deploy:
    image: klakegg/hugo:ext-alpine
    secrets: [SSH]
    commands:
      - scp -i $SSH -P 4545 -r public riq0h@109.123.230.119:~/
